project:
  type: website

website:
  title: "../Daniele_Scanzi/"
  navbar:
    right:
      - text: About
        file: about.qmd
      - text: Projects
      - text: Posts
format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

