project:
  type: website

website:
  title: "~/Daniele-Scanzi"
  navbar:
    right:
      - text: "Projects"
        file: projects/projects_intro.qmd
      - text: "Exploring"
        file: exploring/exploring_intro.qmd
      - text: "Educating"
        file: educating/educating_intro.qmd
      - posts.qmd
        
  sidebar:
    - title: "Projects"
      style: "floating"
      contents:
        - projects/projects_intro.qmd
        - section: "Experiments"
          contents:
            - projects/psychopy_code/coloured_gabor_patches.qmd
        - section: "EEG"
          contents:
            - projects/eeg_matlab_code/eeg_preprocessing_functions.qmd
            
            
    - title: "Exploring"
      style: "floating"
      contents: 
        - exploring/exploring_intro.qmd
        - section: "Aotearoa"
          contents:
            - exploring/waihaha_2023_09_04.qmd
            - exploring/kawakawa_2023_12_26.qmd
        - section: "Italy"
          contents: 
            - exploring/monte_avaro.qmd
        - section: "Trash Running"
          contents:
            - exploring/trash_running.qmd
    - title: "Educating"
      style: "floating"
      contents:
        - educating/educating_intro.qmd
        - section: "Students Review"
          contents:
            - educating/students_review.qmd
        - section: "Bayesian Stat Group"
          contents: 
            - projects/bayesian_stat_material/bayes_intro.qmd
            - projects/bayesian_stat_material/slides_list.qmd
    
format:
  html:
    theme: 
      dark: [cyborg, mystyles.scss]
      light: [cyborg, cyborg_light.scss]
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto  # re-render only when source changes

