project:
  type: website

website:
  title: "~/Daniele-Scanzi"
  navbar:
    right:
      - text: Projects
      - text: Posts
    
format:
  html:
    theme: 
      dark: [cyborg, mystyles.scss]
      light: [cyborg, cyborg_light.scss]
    css: styles.css
    toc: true

editor: visual


