---
title: "Overview"
---

<center><i>A student-led group to learn Bayesian statistics - For students by students</center></i>

This project was initially born when a friend of mine, Dylan Taylor (PhD student at the University of Auckland), and I wanted to meet over lunch to work through the book [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/). Talking with other PhD students, we soon realised that many researchers are interested in applying bayesian stats. However, most students didn't have the opportunity to learn this and feel like learning it alone can be too difficult and time-consuming - a feeling we share too. 
So, we expanded the group to other interested people, and we began a series of weekly meetups. During these, we go through the [2022 lecture series](https://www.youtube.com/watch?v=BYUykHScxj8&list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN) accompanying the book, we have discussions and work through the exercises together.
The group has expanded to around 15 people and has become a great opportunity to learn something useful together and create new connections between like-minded people. 

In this section, you can find the slides and material we create to provide direction during the meetups.  

<center><i><b>This project has now been awarded a [Creating Connections Grant](https://www.auckland.ac.nz/en/students/academic-information/postgraduate-students/doctoral/doctoral-fees-and-money-matters/creating-connections-grant.html) which will help to provide refreshment during the meetups</center></i></b>