---
title: "A Paper a day"
---

## 2024-07-11: [Watson & Pelli, 1983](https://link.springer.com/content/pdf/10.3758/BF03202828.pdf)

Detection or discrimination tasks often require the estimation of each participant's psychometric function to control behavioral performance to a specific threshold. However, obtaining a psychometric function usually requires a high number of trials, as the participant's performance needs to be tested multiple times at a variety of stimulus levels. A way around this is to use an adaptive procedure that incorporates the knowledge acquired from previous trials, as well as the experimenters' knowledge, to estimate the psychometric function's parameters more quickly. Here, Watson and Pelli introduce an adaptive staircase (QUEST), which uses a Bayesian framework to speed up the titration process while retaining high estimation accuracy.

### HOLIDAYS

## 2024-13-06:[Shin et al., 2017](https://elifesciences.org/articles/29086)

Pre-stimulus beta power has been associated with detection and attention
in tactile tasks. Generally, increased sustained pre-stimulus power is
negatively correlated with detection and attention. However, the authors
show that the observed pre-stimulus power likely does not represent
sustained activity. When single-trial time-frequency activity is
analyzed, short bursts of beta activity (beta events) are visible in the
pre-stimulus window. These beta events are not time-locked to a stimulus
and do not appear to be generated by a rhythmic generator. Thus, their
number and timing vary across trials. Because of this, averaging trials
in standard analyses creates the illusion of a sustained beta rhythm. By
analyzing two MEG human datasets and one intracranial recording in mice,
the authors show that the number and timing of the last beta event are
negatively correlated with detection and attention: a higher number of
events corresponds to lower detection, and the closer the last beta
event is to stimulus onset, the lower the detection and attention.
Importantly, the number of events and the timing of the last event
independently affect behavior.

## 2024-12-06: [Voytek & Knight, 2015](https://www.sciencedirect.com/science/article/pii/S0006322315003546)

One of the major features of EEG activity is the 1/f slope visible in
the power spectrum of the data. Although attention is predominantly
given to the oscillatory activity visible in the spectrum (i.e., peaks),
the 1/f slope might contain relevant information reflecting the
excitability state and connectivity of neuronal populations. Here, the
authors start by considering the complex coupling between extracellular
local field potentials (LFP) and firing rates. Specifically, neuronal
spiking is modulated by oscillatory LFPs. LFPs modify the membrane
potentials of postsynaptic neurons, rendering them closer or further
from firing (essentially, LFPs modify the likelihood of a postsynaptic
potential inducing an action potential). The authors propose that this
micro-scale mechanism could be reflected at the meso-scale by
phase-amplitude coupling, where the amplitude of a signal is modulated
by the phase of the oscillatory activity the signal is embedded in.
Moreover, they argue that the effects of LFP activity are reflected in
the 1/f slope. When the LFP activity is "stable" and oscillatory,
neurons are more likely to go through an excitability phase, where
action potentials can be triggered. In this context, a stimulus could
trigger a cascade of action potentials in a neuronal population. If this
happens, many neurons in the population would quickly fire and enter a
refractory period. As this activity is synchronized by the LFP
oscillations, the net refractory period in the population would be
short, resulting in a steep 1/f slope (the aperiodic activity seems to
reflect local population excitation). Conversely, a weak but prolonged
stimulus would induce a higher degree of noise in the population field,
as neurons would not be synchronized, thus inducing a non-coordinated
firing pattern. The result is a net prolonged state of inhibition of the
population, which is reflected as a flattened spectrum. To conclude, a
flattened power spectrum could be a sign of decreased coherence across
cortical areas, as local firing patterns are not synchronized by stable
oscillatory LFP activity. Note, however, that excessive coherence can be
problematic too, as it could create a situation where neuronal firing is
locked to the LFP, resulting in a feedback process that perpetuates
itself. Therefore, a certain amount of "noise," defined as firing
decoupled from the background carrier frequency, is needed for proper
communication across brain areas.

## 2024-11-06: [Yuasa et al., 2023](https://elifesciences.org/reviewed-preprints/90387v1)

Presenting visual stimuli usually induces a decrease in occipital
\[\[alpha power\]\], which is believed to represent increased cortical
excitation. However, both oscillatory and broadband aperiodic activities
are affected by the stimuli. Changes in periodic activity power could be
masked by changes in aperiodic power (e.g., alpha power might increase,
but broadband aperiodic activity might decrease, creating a false null
effect). To address this, the authors used a retinotopic mapping
paradigm (checkerboards moving across space) with ECoG. They separated
the periodic and aperiodic components and observed that stimulus
presentation decreases alpha power at electrodes over visual cortical
areas processing the stimulus. This suggests a retinotopic distribution
of alpha power. Further analysis with pRF showed that both components
have similar pRF centers in the parafovea, but the pRF for alpha power
is larger than for aperiodic activity. This indicates that stimuli
reduce alpha power even when presented peripherally, increasing cortical
excitability and tuning the cortex to process visual information.
Importantly, the stimulus drives \[\[alpha power\]\] changes, not the
other way around (bottom-up, not top-down).

## 2024-10-06: [van der Werf et al., 2022](file:///home/daniele/Zotero/storage/EXGE8JYC/ejn.html)

Electrophysiological studies have observed that the deployment of
attention is a rhythmic process, often associated with neuronal
oscillatory activity around 8 Hz. These observations have been expanded
with behavioural analyses to determine whether the detection of a target
follows an oscillatory pattern. Here, the authors build on previous
studies by estimating behavioural oscillations and relating hit rates to
the length of the cue-target interval. Specifically, they compute the
hit rate in a 50 ms sliding window to obtain a time-resolved hit-rate
measure. The frequency spectrum of the time-resolved hit rate is then
computed to investigate whether the behavioural representation of
attention deployment is dominated by specific frequencies. However, in
this study, they do not observe any effect of frequency on target
detection (i.e., detection is not more common at specific delays from
cue onset). Similarly, they did not find any oscillatory effects at
non-cued locations.

------------------------------------------------------------------------

## 2024-08-06: [Wei et al., 2022](https://link.springer.com/article/10.1007/s11571-022-09862-7)

This study employed an uncued lateralised detection task to investigate
whether the alpha desynchronisation usually observed in these types of
tasks is associated with frontal activity. The assumption is that,
although occipital alpha power might play a role in detecting visual
stimuli, it could be modulated by frontal activity. They observed that
occipital alpha power in the 200ms preceding the stimulus correlates
with hits and misses (low power -\> hit; high power -\> miss). Some
results pointed towards a frontal-to-occipital sweep of alpha power
correlated with hits and misses, moving from a time window further away
from the stimulus towards stimulus presentation (e.g., parieto-central
activity correlates with hits and misses around 500ms before stimulus
onset). However, these correlations were not significant or approached
significance after FDR correction, making this trend difficult to
interpret. Nevertheless, they also observed synchronisation between
frontal theta activity and occipital alpha power, with this
synchronisation being stronger for high alpha power compared to low
power. Moreover, occipital power could be predicted by frontal theta
power.

## 2024-07-06: [Boncompte et al., 2016](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0160347)

Studies on the lateralisation of alpha power commonly use cued designs.
However, hypotheses have been made regarding the possibility of this
lateralisation being generated non-stochastically. To address this, the
authors employed a lateralised design (target appears either in the left
or right hemifield) without using a cue. They compared alpha power
between seen trials (participant saw the target) and unseen trials
(participant missed the target). They observed that, although the
overall occipital alpha power preceding target onset remains constant
between seen and unseen trials, there is significant lateralisation that
distinguishes the two conditions. Specifically, there is higher
lateralisation in seen trials (higher power in the ipsilateral
hemisphere) compared to unseen trials. The crucial aspect here is that
this lateralisation is endogenously driven, as no cues were presented.

## 2024-06-06: [Liu et al., 2023](https://www.sciencedirect.com/science/article/pii/S0301008223000333?via%3Dihub)

Probably one of the most reliable observations in attentional studies
(and working memory) is the lateralization of alpha power — a modulation
in power so that there is lower power in the hemisphere contralateral to
the hemifield where attention was deployed. Here, they show that one
potentially important confound is eye movements, specifically
microsaccades. These small deviations from fixations create a
lateralization of occipital alpha power even in the absence of a task
(here they analyzed the retention period of a working memory paradigm),
meaning that microsaccades alone are able to drive changes in power.
Importantly, they observed that the direction of the alpha power
lateralization is such that power increases ipsilateral to the direction
of the microsaccades, while no effects were observable in the
contralateral hemisphere. Moreover, the effect was greater at P07/P08,
but only weak at central electrodes. These observations pose questions
about how to properly investigate the relationship between alpha power
and attention in lateralized presentations.

## 2024-06-05: [Gao et al., 2020](https://elifesciences.org/articles/61277)

In this paper, Gao and colleagues investigate the *time-scale* property
of neurons. Specifically, neurons across the cortex must be able to
maintain and process information at different time scales: from brief
moments necessary to react to a stimulus, to seconds, minutes, and even
years, as in working memory and memory. The time scale of different
cortical areas was estimated from the PSD of ECoG recordings, exploiting
the fact that the time-scale factor can be calculated from the *knee
frequency* in the power spectrum. They then correlated the time-scale
values with measures of myelination, cortical thickness, gene
expression, and working memory performance. They observed that time
scales are correlated with all these measures, suggesting that the
micro- and macro-scale structural and functional organization of the
brain allows for the emergence of an organized time-scale structure.
Indeed, sensorimotor and visual areas showed faster time scales, while
association regions showed longer time scales, reflecting the different
types of information processing they perform. Note that this hierarchy
has been observed in both humans and macaques. This time scale also
varies as a function of cognitive activity (e.g., time scale increases
with increased cognitive load) and aging (on average, the time scale
decreases).

## 2024-06-04: [Keesey & Nichols, 1967](https://www.sciencedirect.com/science/article/pii/0042698967900077?via%3Dihub)

The authors investigate the relationship between the time dynamics of
individual alpha power and the fading out of stabilized fixated images.
They used a collimator system mounted on a contact lens to stabilize a
patch of light on the participant's retina while recording EEG. They
observed that alpha power increases over a 1-second period before the
participant reports the subjective disappearing of the image from
conscious perception. Alpha power decreases after the participant
reports the reappearing of the stimulus (though the change in alpha is
more variable in time). They also observed that reappearance of the
image was preceded by large eye movements or blinks in 40% of the
trials. In a control condition where the image was not stabilized and
the disappearance of the stimulus was mimicked by either defocusing the
stimulus or lowering its luminance to zero, they observed that alpha
powerchanges only after the participant reports the change in subjective
perception. Putting it all together, it seems that alpha power might
control the perception of luminous stimuli when the visual system cannot
rely on eye movements to update the retinal image. Here, the authors
suggest the possibility that in this condition, alpha replaces the
missing signal associated with the visual input.
